### ISSUE TITLE
Follower Counter not visualized

### ISSUE THREAD

**Issue by Rpinnkss** [marconicivitavecchia/IFC-Frontend-dev#1]
![Front End issue](https://github.com/marconicivitavecchia/IFC-Frontend-dev/assets/124357976/13915842-7e58-431d-b9b9-f9ced1e14a6c)

follower-content color in CSS must be changed.

**Comment by DavidePiccione** [comment]
@marconicivitavecchia/frontend potete dare un'occhiata?

**Comment by DavidePiccione** [comment]
Risolto in 29ef203
